title = "Lurk Server Tracing Configuration"

[layer.app]
type = "fmt"
writer = "stdout"
formatter = "compact"
span_events = "none"
target = false
ansi = true

[writer.stdout]
type = "standard_output"

[filter.root]
level = "info"
